### PR TITLE
Rewrite of how GUI get infomation

### LINKED ISSUE #121: Hiring button doesn't hire the correct sim
Intermittent issue where more than one sim is available, when you click on a sim to hire them they don't pick the right sim and can cause an issue where it hires the wrong sim and then hiring them again doesn't work but then you can't fire them from the first one.

Feel from to ask more about this if you need

### PR DESCRIPTION
**Pull request by aidie8**
I have made it send specific information of each sim instead of relying on the client to be able to gather that infomation, this has made it more robust in showing information in the UI's, Needs a lot of testing to make sure i am not breaking more things, I have tested the basic, does it function as coded but not edge cases, i also fixed a few bugs such as when clicking on a button with a certain name it selects the wrong sim, stupid math that i did not do correctly

### CODE REVIEW

**Comment by aidie8** [comment]
This should address #122, #121, just confirm these for me, I always miss things as usual

**Review by fabbe50 — APPROVED** [review]
These changes seem to fix both #121 and #122.

Testing procedure includes:
* Teleporting in and out of chunks several times waiting for chunks to unload.
* Flying in and out of chunks several times waiting for chunks to unload.
* Hiring several sims to different jobs while having several unemployed sims.

Conclusion:
* Seems to work well.
* It doesn't crash.

**Comment by fabbe50** [comment]
On second note, I don't know if unloaded sims are handled by the housing system.

**Comment by aidie8** [comment]
I did work on the TileResidential, and GuiResidential which are both used in the housing system. its what lead me to this issue in the first place.
I tested,
- Creating a house
- letting someone move in
- hiring them at least 5-6 chunks away
- setting render distance to 2
- going back to see if the house still shows occupants


this did work for me

**Pull request merged**
